'use client';

import '../style/tailwind.css';
import { Roboto } from 'next/font/google';
import StyledComponentsRegistry from '@/lib/StyledComponentsRegistry';
import { GlobalStyle } from '../style/global';

const roboto = Roboto({ weight: '400', subsets: ['latin'] });

export const metadata = {
	title: 'test',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
	return (
		<html lang='pt-BR'>
			<body className={roboto.className}>
				<StyledComponentsRegistry>
					<GlobalStyle />
					{children}
				</StyledComponentsRegistry>
			</body>
		</html>
	);
}
